# Generated by Django 2.2.7 on 2019-11-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelanggan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('berat', models.DecimalField(decimal_places=1, max_digits=15)),
                ('tambahan', models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                ('harga', models.DecimalField(decimal_places=1, default=6000, max_digits=15)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggan.Customer')),
            ],
        ),
    ]
