# Generated by Django 2.2.7 on 2019-11-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='berat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='harga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tambahan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
