# Generated by Django 2.2.7 on 2019-11-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191117_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust', to='pelanggan.Customer'),
        ),
    ]
