# Generated by Django 2.2.7 on 2019-11-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191118_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Total',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
