# Generated by Django 2.2.7 on 2019-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
