# Generated by Django 2.2.7 on 2019-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191118_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='tgl_selesai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
