# Generated by Django 2.2.7 on 2019-11-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191119_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tgl_selesai',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
